// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeakerApi.Data;

namespace SpeakerApi.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    partial class SpeakerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SpeakerLibrary.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "998ca356-5c0a-4d4e-ab53-08b1b71a639d",
                            City = "Vancouver",
                            Email = "tday@amazon.com",
                            Employer = "Amazon",
                            FirstName = "Tom",
                            LastName = "Day",
                            MobileNumber = "604-111-1111",
                            Province = "BC",
                            Specialization = "AWS"
                        },
                        new
                        {
                            SpeakerId = "1ed2051c-ecf6-4d66-9110-c33850d84754",
                            City = "Calgary",
                            Email = "afox@microsoft.com",
                            Employer = "Microsoft",
                            FirstName = "Ann",
                            LastName = "Fox",
                            MobileNumber = "604-222-2222",
                            Province = "AB",
                            Specialization = "Dotnet"
                        },
                        new
                        {
                            SpeakerId = "f4f5dc84-ea0c-470e-ab0a-c88a52fcb5d1",
                            City = "Toronto",
                            Email = "aash@meta.com",
                            Employer = "Meta",
                            FirstName = "Art",
                            LastName = "Ash",
                            MobileNumber = "604-333-3333",
                            Province = "ON",
                            Specialization = "Oculus"
                        },
                        new
                        {
                            SpeakerId = "8becc722-96fc-4b9b-aaa9-b5d22b045fea",
                            City = "Montreal",
                            Email = "mhay@yahoo.com",
                            Employer = "Yahoo",
                            FirstName = "Mia",
                            LastName = "Hay",
                            MobileNumber = "604-444-4444",
                            Province = "QB",
                            Specialization = "Yahoo Search"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
